{% set name = "povray" %}
{% set version = "3.8.0-x.10064738" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/POV-Ray/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: c334d5a67e8d87afdc9808a37f27ee2e0bd251775dfe07fae659adb21f1d01c5

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - automake
    - make
  host:
    - boost-cpp =1.72.0
    - libpng
    - jpeg
    - libtiff
    - zlib
  run:
    - boost-cpp =1.72.0

test:
  commands:
    - povray --version

about:
  home: http://www.povray.org
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: The Persistence of Vision Raytracer

  description: |
    The Persistence of Vision Raytracer is a high-quality, Free Software 
    tool for creating stunning three-dimensional graphics. The source code 
    is available for those wanting to do their own ports.
  doc_url: http://www.povray.org/documentation/
  dev_url: https://github.com/POV-Ray/povray

extra:
  recipe-maintainers:
    - jan-janssen
